makefile.depends:  ./src/dominatorData.cc ./src/ConfigExtract.cc ./src/Annotations.cc ./src/loopAnalysis.cc ./src/dominatorAnalysis.cc ./src/HeptaneExtract.cc ./src/switchAnalysis.cc
obj/dominatorData.o: src/dominatorData.cc src/dominatorData.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/dominatorData.cc -o obj/dominatorData.o 
obj/ConfigExtract.o: src/ConfigExtract.cc src/ConfigExtract.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/ParsingStructure.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionType.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionFormat.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/DAAInstruction.h \
 /data/src/HeptaneExtract/../Common/utl/src/Logger.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/ConfigExtract.cc -o obj/ConfigExtract.o 
obj/Annotations.o: src/Annotations.cc src/Annotations.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h \
 src/ConfigExtract.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/ParsingStructure.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionType.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionFormat.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/DAAInstruction.h \
 /data/src/HeptaneExtract/../Common/utl/src/Logger.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/GlobalAttributes.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/SymbolTableAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/ARMWordsAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/MetaInstructionAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/LoopTree.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/Annotations.cc -o obj/Annotations.o 
obj/loopAnalysis.o: src/loopAnalysis.cc src/loopAnalysis.h \
 src/dominatorData.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/loopAnalysis.cc -o obj/loopAnalysis.o 
obj/dominatorAnalysis.o: src/dominatorAnalysis.cc src/dominatorAnalysis.h \
 src/dominatorData.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/dominatorAnalysis.cc -o obj/dominatorAnalysis.o 
obj/HeptaneExtract.o: src/HeptaneExtract.cc src/ConfigExtract.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/ParsingStructure.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionType.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionFormat.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/DAAInstruction.h \
 /data/src/HeptaneExtract/../Common/utl/src/Logger.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h \
 src/dominatorAnalysis.h src/loopAnalysis.h src/switchAnalysis.h \
 src/Annotations.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/GlobalAttributes.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/SymbolTableAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/ARMWordsAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/MetaInstructionAttribute.h \
 /data/src/HeptaneExtract/../Common/utl/src/Utl.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/HeptaneExtract.cc -o obj/HeptaneExtract.o 
obj/switchAnalysis.o: src/switchAnalysis.cc \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/GlobalAttributes.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CfgLib.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributed.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Attributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Serialisable.h \
 /data/src/HeptaneExtract/../cfglib_install//include/XmlExtra.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /data/src/HeptaneExtract/../cfglib_install//include/CloneHandle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Factory.h \
 /data/src/HeptaneExtract/../cfglib_install//include/SerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/PointerAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Handle.h \
 /data/src/HeptaneExtract/../cfglib_install//include/NonSerialisableAttributes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Node.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Instruction.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Edge.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Loop.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Program.h \
 /data/src/HeptaneExtract/../Common/utl/src/HeptaneStdTypes.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Cfg.h \
 /data/src/HeptaneExtract/../cfglib_install//include/Helper.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/SymbolTableAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/ARMWordsAttribute.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/MetaInstructionAttribute.h \
 src/switchAnalysis.h src/ConfigExtract.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/ParsingStructure.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionType.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/InstructionFormat.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/arch.h \
 /data/src/HeptaneExtract/../Common/ArchitectureDependent/src/DAAInstruction.h \
 /data/src/HeptaneExtract/../Common/utl/src/Logger.h \
 /data/src/HeptaneExtract/../Common/GlobalAttributes/src/AddressAttribute.h
	mkdir obj 2>/dev/null || true 
	g++ -O3 -Wall -DLINUX -Isrc  -I/usr/include/libxml2 -I/data/src/HeptaneExtract/../cfglib_install//include -I/data/src/HeptaneExtract/../Common/GlobalAttributes/src -I/data/src/HeptaneExtract/../Common/utl/src -I/data/src/HeptaneExtract/../Common/ArchitectureDependent/src -c src/switchAnalysis.cc -o obj/switchAnalysis.o 
